Fix Maximum function nesting level
Fixes possible tests errors because of missing $error variable
Fatal error: Maximum function nesting level of '100' reached, aborting!